//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.9.6.
// xmiu_res.rc

#define IDC_DO_HELP                         1000
#define IDC_FIND_EDIT                       1001
#define IDC_FIND_NEXT                       1002
#define IDC_FIND_CANCEL                     1003
#define IDC_FIND_CASE                       1004
#define IDC_FIND_WORD                       1005
#define IDC_FIND_REGEX                      1006
#define IDC_REPLACE_EDIT                    1007
#define IDC_REPLACE_BTN                     1008
#define IDC_REPLACE_ALL_BTN                 1009
#define IDC_REPLACE_LABEL                   1010
#define IDC_GOTO_LABEL                      1011
#define IDC_GOTO_EDIT                       1012
#define IDC_TOGGLE_FULLSCREEN               1013

#define IDD_FIND_DIALOG                     102
#define IDD_GOTO_DIALOG                     103

#define IDI_ICON1                           101

#define IDR_MAINACCEL                       100

#define IDS_APP_TITLE                       104
#define IDS_UNTITLED                        105
#define IDS_HELP_TEXT                       106
#define IDS_FIND_TITLE                      107
#define IDS_REPLACE_TITLE                   108
#define IDS_REPLACE_DONE                    109
#define IDS_REPLACE_COUNT                   110
#define IDS_CONFIRM_TITLE                   111
#define IDS_SAVE_PROMPT                     112
#define IDS_ERROR_TITLE                     113
#define IDS_OPEN_ERROR                      114
#define IDS_TEMP_FILE_ERR                   115
#define IDS_WRITE_ERR                       116
#define IDS_SAVE_ERR                        117
#define IDS_FATAL_ERROR                     118
#define IDS_REOPEN_ERR                      119
#define IDS_OPEN_FAIL                       120
#define IDS_FILE_CHANGED_EXT                121
#define IDS_FILE_CHANGED_WARN               122
#define IDS_FILE_CHANGED_TITLE              123

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1013
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
