//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.9.6.
// xmiu_res.rc

#define IDC_FIND_EDIT                       1001
#define IDC_FIND_NEXT                       1002
#define IDC_FIND_CANCEL                     1003
#define IDC_FIND_CASE                       1004
#define IDC_FIND_WORD                       1005
#define IDC_FIND_REGEX                      1006
#define IDC_REPLACE_EDIT                    1007
#define IDC_REPLACE_BTN                     1008
#define IDC_REPLACE_ALL_BTN                 1009
#define IDC_REPLACE_LABEL                   1010
#define IDC_GOTO_LABEL                      1011
#define IDC_GOTO_EDIT                       1012

#define IDD_FIND_DIALOG                     102
#define IDD_GOTO_DIALOG                     103
#define IDD_ABOUT                           104
#define IDD_CONFIG                          105

#define IDI_ICON1                           101

#define IDR_MAINACCEL                       100
#define IDR_MAINMENU                        101

#define IDS_APP_TITLE                       104
#define IDS_UNTITLED                        105
#define IDS_HELP_TEXT                       106
#define IDS_FIND_TITLE                      107
#define IDS_REPLACE_TITLE                   108
#define IDS_REPLACE_DONE                    109
#define IDS_REPLACE_COUNT                   110
#define IDS_CONFIRM_TITLE                   111
#define IDS_SAVE_PROMPT                     112
#define IDS_ERROR_TITLE                     113
#define IDS_OPEN_ERROR                      114
#define IDS_TEMP_FILE_ERR                   115
#define IDS_WRITE_ERR                       116
#define IDS_SAVE_ERR                        117
#define IDS_FATAL_ERROR                     118
#define IDS_REOPEN_ERR                      119
#define IDS_OPEN_FAIL                       120
#define IDS_FILE_CHANGED_EXT                121
#define IDS_FILE_CHANGED_WARN               122
#define IDS_FILE_CHANGED_TITLE              123
#define IDS_README                          124

#define ID_EXIT                             10001
#define ID_SAVE_AS                          10002
#define ID_TOGGLE_FULLSCREEN                10013
#define ID_FIND_NEXT                        10014
#define ID_FIND_PREV                        10015
#define ID_SHOW_FIND                        10016
#define ID_SHOW_REPLACE                     10017
#define ID_OPEN                             10018
#define ID_NEW                              10019
#define ID_SAVE                             10020
#define ID_UNDO                             10021
#define ID_REDO                             10022
#define ID_COPY                             10023
#define ID_CUT                              10024
#define ID_PASTE                            10025
#define ID_SELECT_NEXT_OCCURRENCE           10026
#define ID_GO_TO_LINE                       10027
#define ID_DELETE_LINES                     10028
#define ID_UPPERCASE                        10029
#define ID_LOWERCASE                        10030
#define ID_ZOOM_IN                          10031
#define ID_ZOOM_OUT                         10032
#define ID_SELECT_ALL                       10033
#define ID_ZOOM_100                         10038
#define ID_INSERT_MODE                      10039
#define ID_INDENT                           10040
#define ID_UNINDENT                         10041
#define ID_DELETE                           10042
#define ID_ESCAPE                           10043
#define ID_WORD_WRAP_MODE                   10044
#define ID_MOVE_LINES_UP                    10045
#define ID_MOVE_LINES_DOWN                  10046
#define ID_DUPLICATE_LINES_UP               10047
#define ID_DUPLICATE_LINES_DOWN             10048
#define ID_FORCE_INDENT                     10049
#define ID_JUMP_TO_MATCHING_BRACKET         10050
#define ID_MOVE_LEFT                        10052
#define ID_MOVE_SHIFT_LEFT                  10053
#define ID_MOVE_CONTROL_LEFT                10054
#define ID_MOVE_CONTROL_SHIFT_LEFT          10055
#define ID_MOVE_RIGHT                       10056
#define ID_MOVE_SHIFT_RIGHT                 10057
#define ID_MOVE_CONTROL_RIGHT               10058
#define ID_MOVE_CONTROL_SHIFT_RIGHT         10059
#define ID_MOVE_UP                          10060
#define ID_MOVE_SHIFT_UP                    10061
#define ID_MOVE_CONTROL_UP                  10062
#define ID_MOVE_CONTROL_SHIFT_UP            10063
#define ID_MOVE_DOWN                        10064
#define ID_MOVE_SHIFT_DOWN                  10065
#define ID_MOVE_CONTROL_DOWN                10066
#define ID_MOVE_CONTROL_SHIFT_DOWN          10067
#define ID_MOVE_HOME                        10068
#define ID_MOVE_SHIFT_HOME                  10069
#define ID_MOVE_CONTROL_HOME                10070
#define ID_MOVE_CONTROL_SHIFT_HOME          10071
#define ID_MOVE_END                         10072
#define ID_MOVE_SHIFT_END                   10073
#define ID_MOVE_CONTROL_END                 10074
#define ID_MOVE_CONTROL_SHIFT_END           10075
#define ID_MOVE_PRIOR                       10076
#define ID_MOVE_SHIFT_PRIOR                 10077
#define ID_MOVE_CONTROL_PRIOR               10078
#define ID_MOVE_CONTROL_SHIFT_PRIOR         10079
#define ID_MOVE_NEXT                        10080
#define ID_MOVE_SHIFT_NEXT                  10081
#define ID_MOVE_CONTROL_NEXT                10082
#define ID_MOVE_CONTROL_SHIFT_NEXT          10083
#define ID_OPEN_README                      10084
#define ID_ABOUT                            10085
#define ID_CONFIG                           10086

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    102
        #define _APS_NEXT_COMMAND_VALUE     10087
        #define _APS_NEXT_CONTROL_VALUE     1013
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
