//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.9.6.
// xmiu_res.rc

#define IDC_DO_HELP                         1000
#define IDC_FIND_EDIT                       1001
#define IDC_FIND_NEXT                       1002
#define IDC_FIND_CANCEL                     1003
#define IDC_FIND_CASE                       1004
#define IDC_FIND_WORD                       1005
#define IDC_FIND_REGEX                      1006
#define IDC_REPLACE_EDIT                    1007
#define IDC_REPLACE_BTN                     1008
#define IDC_REPLACE_ALL_BTN                 1009
#define IDC_REPLACE_LABEL                   1010
#define IDC_GOTO_LABEL                      1011
#define IDC_GOTO_EDIT                       1012
#define IDC_TOGGLE_FULLSCREEN               1013
#define IDC_DO_FIND_NEXT                    1014
#define IDC_DO_FIND_PREV                    1015
#define IDC_SHOW_FIND                       1016
#define IDC_SHOW_REPLACE                    1017
#define IDC_DO_OPEN                         1018
#define IDC_DO_NEW                          1019
#define IDC_DO_SAVE                         1020
#define IDC_DO_UNDO                         1021
#define IDC_DO_REDO                         1022
#define IDC_DO_COPY                         1023
#define IDC_DO_CUT                          1024
#define IDC_DO_PASTE                        1025
#define IDC_SELECT_NEXT_OCCURRENCE          1026
#define IDC_GO_TO_LINE                      1027
#define IDC_DELETE_LINES                    1028
#define IDC_UPPERCASE                       1029
#define IDC_LOWERCASE                       1030
#define IDC_ZOOM_IN                         1031
#define IDC_ZOOM_OUT                        1032
#define IDC_SELECT_ALL                      1033
#define IDC_MOVE_UP                         1034
#define IDC_MOVE_SELECT_UP                  1035
#define IDC_MOVE_DOWN                       1036
#define IDC_MOVE_SELECT_DOWN                1037
#define IDC_ZOOM_100                        1038
#define IDC_INSERT_MODE                     1039
#define IDC_INDENT                          1040
#define IDC_UNINDENT                        1041
#define IDC_DELETE                          1042
#define IDC_ESCAPE                          1043

#define IDD_FIND_DIALOG                     102
#define IDD_GOTO_DIALOG                     103

#define IDI_ICON1                           101

#define IDR_MAINACCEL                       100

#define IDS_APP_TITLE                       104
#define IDS_UNTITLED                        105
#define IDS_HELP_TEXT                       106
#define IDS_FIND_TITLE                      107
#define IDS_REPLACE_TITLE                   108
#define IDS_REPLACE_DONE                    109
#define IDS_REPLACE_COUNT                   110
#define IDS_CONFIRM_TITLE                   111
#define IDS_SAVE_PROMPT                     112
#define IDS_ERROR_TITLE                     113
#define IDS_OPEN_ERROR                      114
#define IDS_TEMP_FILE_ERR                   115
#define IDS_WRITE_ERR                       116
#define IDS_SAVE_ERR                        117
#define IDS_FATAL_ERROR                     118
#define IDS_REOPEN_ERR                      119
#define IDS_OPEN_FAIL                       120
#define IDS_FILE_CHANGED_EXT                121
#define IDS_FILE_CHANGED_WARN               122
#define IDS_FILE_CHANGED_TITLE              123

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1018
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
